export enum DebtType {
  CREDIT_CARD = 'CREDIT_CARD',
  PERSONAL_LOAN = 'PERSONAL_LOAN',
  COMPANY = 'COMPANY',
  OTHER = 'OTHER',
}

export enum DebtRange {
  Range1 = '5.000.000-10.000.000',
  Range2 = '10.000.000-20.000.000',
  Range3 = '20.000.000-50.000.000',
  Range4 = '50.000.000-100.000.000',
  Range5 = '+100.000.000',
}

export enum DebtEntity {
  BANCOLOMBIA = 'BANCOLOMBIA',
  BANCO_PICHINCHA = 'BANCO_PICHINCHA',
  BANCO_AV_VILLAS = 'BANCO_AV_VILLAS',
  BANCO_POPULAR = 'BANCO_POPULAR',
  BANCO_OCCIDENTE = 'BANCO_OCCIDENTE',
  BANCO_AGRARIO = 'BANCO_AGRARIO',
  BANCO_DE_BOGOTA = 'BANCO_DE_BOGOTA',
  BANCO_DE_OCCIDENTE = 'BANCO_DE_OCCIDENTE',
  BANCO_DE_POPULAR = 'BANCO_DE_POPULAR',
  BANCO_FALABELLA = 'BANCO_FALABELLA',
  BANCO_SANTANDER = 'BANCO_SANTANDER',
  BANCO_SCOTIABANK = 'BANCO_SCOTIABANK',
  OTHER = 'OTHER',
}
